
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox10;

	private global::Gtk.Label label4;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button button40;

	private global::Gtk.Button button42;

	private global::Gtk.Button button44;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		// Container child vbox10.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("<span font=\"32\">Label Text</span>");
		this.label4.UseMarkup = true;
		this.vbox10.Add(this.label4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label4]));
		w1.Position = 0;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.HeightRequest = 60;
		this.hbox2.Name = "hbox2";
		// Container child hbox2.Gtk.Box+BoxChild
		this.button40 = new global::Gtk.Button();
		this.button40.CanFocus = true;
		this.button40.Name = "button40";
		this.button40.UseUnderline = true;
		this.button40.Label = global::Mono.Unix.Catalog.GetString("GtkButton2");
		this.hbox2.Add(this.button40);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button40]));
		w2.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button42 = new global::Gtk.Button();
		this.button42.CanFocus = true;
		this.button42.Name = "button42";
		this.button42.UseUnderline = true;
		this.button42.Label = global::Mono.Unix.Catalog.GetString("GtkButton3");
		this.hbox2.Add(this.button42);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button42]));
		w3.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button44 = new global::Gtk.Button();
		this.button44.WidthRequest = 160;
		this.button44.CanFocus = true;
		this.button44.Name = "button44";
		this.button44.UseUnderline = true;
		this.button44.Label = global::Mono.Unix.Catalog.GetString("GtkButton4");
		this.hbox2.Add(this.button44);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button44]));
		w4.PackType = ((global::Gtk.PackType)(1));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox10.Add(this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox2]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.Add(this.vbox10);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 591;
		this.DefaultHeight = 258;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
